name: Build and Release EXE

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -e .

      - name: Build executable
        run: |
          pyinstaller --onefile --name wem2csv wem2csv/cli.py

      - name: Verify build output
        shell: pwsh
        run: |
          if (!(Test-Path "dist/wem2csv.exe")) {
            Write-Error "Build failed: wem2csv.exe not found"
            exit 1
          }
          Get-ChildItem -Path dist

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: wem2csv-exe
          path: dist/wem2csv.exe

  release:
    needs: build-windows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download EXE artifact
        uses: actions/download-artifact@v4
        with:
          name: wem2csv-exe
          path: ./dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/wem2csv.exe
            LICENSE
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
